ALTER TABLE "AnswerUpvote" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Badge" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Bookmark" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "CaseProgress" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "CaseSolution" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ContentView" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "CorrectAnswer" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Document" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Document_to_Tag" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ForumAnswer" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ForumQuestion_to_Subfield" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ForumQuestion_to_Topic" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ForumQuestion" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ForumQuestion_to_LegalField" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "GameProgress" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Note" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "NotificationType" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Ping" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ProfilePicture" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "QuestionUpvote" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ReferralBalance" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ReferralCode" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Referral" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "SearchIndexUpdateQueue" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "Streak" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "StreakActivities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "UpdateUserInCrmQueue" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "UploadFolder" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "UploadedFile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "UploadedFile_to_Tag" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "UserRole" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "User_to_Badge" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "User_to_Role" ENABLE ROW LEVEL SECURITY;