import * as fs from 'fs';
import * as path from 'path';

const srcDir = 'src';
const schemasDir = "schemas";
const commonValidationDir = "common";
const schemaPattern = /\.schema\.ts$/;
const commonValidationPattern = /\.validation\.ts$/;
const indexFile = path.join(srcDir, 'exports.ts');

function findSchemaFiles(dir, pattern) {
  const results = [];

  const files = fs.readdirSync(dir);

  for (const file of files) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      results.push(...findSchemaFiles(fullPath, pattern));
    } else if (pattern.test(file)) {
      // Convert Windows paths to forward slashes if necessary
      const relativePath = path.relative(srcDir, fullPath)
        .replace(/\\/g, '/');

      // Remove the .ts extension
      const importPath = './' + relativePath.replace(/\.ts$/, '');
      results.push(importPath);
    }
  }

  return results;
}

function generateIndex() {
  const schemaFiles = findSchemaFiles(`${srcDir}/${schemasDir}`, schemaPattern);
  const commonValidationFiles = findSchemaFiles(`${srcDir}/${commonValidationDir}`, commonValidationPattern);

  const allFiles = [...schemaFiles, ...commonValidationFiles];

  const exports = allFiles
    .sort()
    .map(file => `export * from "${file}";`)
    .join('\n');

  const warning = "/* ==================== CAUTION: This file is automatically generated. Do not edit. ==================== */\n\n";

  fs.writeFileSync(indexFile, warning + exports + '\n');

  console.log(`Generated ${allFiles.length} exports in ${indexFile}`);
}

// Run the script
generateIndex();