INSERT INTO "Badge" ("Name", "Description", "ImageFilename") VALUES
    ('Great Achiever', 'Earned for outstanding performance', 'cases-great-job-1.svg'),
    ('Power User', 'Active and engaged forum member', 'forum-power-user.svg'),
    ('Longevity Champion', 'For long-term dedication', 'general-longevity.svg'),
    ('Master of Cases', 'Achieved mastery in case solving', 'cases-master-of.svg'),
    ('Forum Pro', 'Active and helpful in the forum', 'forum-pro.svg'),
    ('Perfect Week Achiever', 'Consistency is the key', 'general-perfect-week.svg'),
    ('Smart Guy 10', 'Reached a score of 10', 'cases-smart-guy-10.svg'),
    ('One of 100', 'Among the top 100 participants', 'general-1-of-100.svg'),
    ('Play and Learn 25', 'Learned through playing 25 times', 'general-play-and-learn-25.svg'),
    ('Smart Guy 25', 'Achieved a score of 25', 'cases-smart-guy-25.svg'),
    ('Three-Day Streak', 'Consistently active for 3 days', 'general-3-days.svg'),
    ('Play and Learn 3', 'Learned through playing 3 times', 'general-play-and-learn-3.svg'),
    ('Smart Guy 5', 'Reached a score of 5', 'cases-smart-guy-5.svg'),
    ('Dedication Awardee', 'Recognizing your dedication', 'general-dedication.svg'),
    ('Play and Learn 50', 'Learned through playing 50 times', 'general-play-and-learn-50.svg'),
    ('Master of Dictionary', 'A master of words', 'dictionary-master-of.svg'),
    ('Favorites Collector', 'You love our content', 'general-favourites-1.svg'),
    ('Power User', 'An influential power user', 'general-power-user.svg'),
    ('Active Member 1', 'Actively contributing since day 1', 'forum-active-member-1.svg'),
    ('Feedback Guru', 'Providing valuable feedback', 'general-feedback-1.svg'),
    ('UGC Uploader 1', 'First to share user-generated content', 'ugc-upload-1.svg'),
    ('Active Member 10', 'A dedicated member for 10 days', 'forum-active-member-10.svg'),
    ('Feedback Master', 'Master of providing feedback', 'general-feedback-10.svg'),
    ('UGC Uploader 10', 'Sharing user-generated content for 10 days', 'ugc-upload-10.svg'),
    ('Active Member 5', 'Consistently active for 5 days', 'forum-active-member-5.svg'),
    ('Feedback Enthusiast', 'Enthusiastic about giving feedback', 'general-feedback-5.svg'),
    ('UGC Uploader 5', 'Sharing user-generated content for 5 days', 'ugc-upload-5.svg');
