/* eslint-disable max-lines */
import { type FunctionComponent } from "react";

export const SearchPageHeaderBgLayer: FunctionComponent = () => (
  <svg
    width="1438"
    height="239"
    viewBox="0 0 1438 239"
    fill="none"
    xmlns="http://www.w3.org/2000/svg">
    <g clipPath="url(#clip0_3124_128)">
      <g opacity="0.2">
        <rect
          x="14"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="39.1786"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="64.3572"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="89.5357"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="114.714"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="139.893"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="165.071"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="190.25"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="215.429"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="240.607"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="265.786"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="290.964"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="316.143"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="341.321"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="366.5"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="391.679"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="416.857"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="442.036"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="467.214"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="492.393"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="517.571"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="542.75"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="567.929"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="593.107"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="618.286"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="643.464"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="668.643"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="693.821"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="719"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="744.179"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="769.357"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="794.536"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="819.714"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="844.893"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="870.072"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="895.25"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="920.429"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="945.607"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="970.786"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="995.965"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1021.14"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1046.32"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1071.5"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1096.68"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1121.86"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1147.04"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1172.21"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1197.39"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1222.57"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1247.75"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1272.93"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1298.11"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1323.29"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1348.46"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1373.64"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1398.82"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
        <rect
          x="1424"
          y="-39"
          width="1"
          height="470"
          fill="white"
        />
      </g>
      <g opacity="0.2">
        <rect
          x="-2"
          y="235.059"
          width="1"
          height="1440"
          transform="rotate(-90 -2 235.059)"
          fill="white"
        />
        <rect
          x="-2"
          y="209.354"
          width="1"
          height="1440"
          transform="rotate(-90 -2 209.354)"
          fill="white"
        />
        <rect
          x="-2"
          y="183.646"
          width="1"
          height="1440"
          transform="rotate(-90 -2 183.646)"
          fill="white"
        />
        <rect
          x="-2"
          y="157.941"
          width="1"
          height="1440"
          transform="rotate(-90 -2 157.941)"
          fill="white"
        />
        <rect
          x="-2"
          y="132.236"
          width="1"
          height="1440"
          transform="rotate(-90 -2 132.236)"
          fill="white"
        />
        <rect
          x="-2"
          y="106.529"
          width="1"
          height="1440"
          transform="rotate(-90 -2 106.529)"
          fill="white"
        />
        <rect
          x="-2"
          y="80.8242"
          width="1"
          height="1440"
          transform="rotate(-90 -2 80.8242)"
          fill="white"
        />
        <rect
          x="-2"
          y="55.1172"
          width="1"
          height="1440"
          transform="rotate(-90 -2 55.1172)"
          fill="white"
        />
        <rect
          x="-2"
          y="29.4121"
          width="1"
          height="1440"
          transform="rotate(-90 -2 29.4121)"
          fill="white"
        />
        <rect
          x="-2"
          y="3.70508"
          width="1"
          height="1440"
          transform="rotate(-90 -2 3.70508)"
          fill="white"
        />
      </g>
      <rect width="1438" height="238" fill="url(#paint0_radial_3124_128)"/>
    </g>
    <defs>
      <radialGradient
        id="paint0_radial_3124_128"
        cx="0"
        cy="0"
        r="1"
        gradientUnits="userSpaceOnUse"
        gradientTransform="translate(719 119) rotate(90) scale(119 719)">
        <stop stopColor="#9B1E14" stopOpacity="0"/>
        <stop offset="1" stopColor="#A90000"/>
      </radialGradient>
      <clipPath id="clip0_3124_128">
        <rect width="1438" height="240" fill="white"/>
      </clipPath>
    </defs>
  </svg>
);

