# ========= Use this file for development only! =========

version: '3.9'

services:

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./meilisearch/.env
    ports:
      - '7700:7700'
    volumes:
      - ./meilisearch/data:/meili_data

  caddy:
    image: caddy:2.4.3-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/data/certs
      - ./caddy/data:/data
      - ./caddy/config:/config

