# ========= Use this file for development only! =========

version: '3.9'

services:

#  mariadb:
#    image: mariadb
#    restart: always
#    container_name: mariadb
#    volumes:
#      - './db/data:/var/lib/mysql'
#    env_file:
#      - db/.env
#      - db/.env.local
#    ports:
#      - '3306:3306'

  constellatio-app:
    container_name: constellatio-app
    restart: always
    image: constellatio-app-dev
    env_file:
      - ./app/.env
      - ./app/.env.local
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - './app:/usr/src/app'
      - '/usr/src/app/node_modules'
      - '/usr/src/app/.yarn/cache'
    ports:
      - '3010:3000'

  caddy:
    image: caddy:2.4.3-alpine
    container_name: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/data/certs
      - ./caddy/data:/data
      - ./caddy/config:/config
