packages:
  - workspace/packages/*
  - workspace/tooling/*
  - workspace/app

catalog:
  "@google-cloud/storage": 7.13.0
  "@supabase/auth-helpers-nextjs": 0.10.0
  "@supabase/auth-helpers-react": 0.5.0
  "@supabase/ssr": 0.5.1
  "@t3-oss/env-nextjs": 0.10.1
  "@tanstack/react-query": 5.59.15
  "@total-typescript/ts-reset": 0.6.1
  "@trpc/client": 11.0.0-rc.569
  "@trpc/next": 11.0.0-rc.569
  "@trpc/react-query": 11.0.0-rc.569
  "@trpc/server": 11.0.0-rc.569
  "@types/node": 20.17.5
  "axios": 1.7.7
  "date-fns": 4.1.0
  "eslint": 8.57.0
  "meilisearch": 0.44.1
  "next": 14.2.15
  "postgres": 3.4.5
  "supabase": 1.226.3
  "stripe": 16.9.0
  "superjson": 2.2.1
  "typescript": 5.5.4
  "zod": 3.23.8

