packages:
  - workspace/packages/*
  - workspace/tooling/*
  #- workspace/app

catalog:
  "@supabase/auth-helpers-nextjs": 0.10.0
  "@supabase/auth-helpers-react": 0.5.0
  "@t3-oss/env-nextjs": 0.10.1
  "@tanstack/react-query": 5.59.15
  "@trpc/client": 11.0.0-rc.569
  "@trpc/next": 11.0.0-rc.569
  "@trpc/react-query": 11.0.0-rc.569
  "@trpc/server": 11.0.0-rc.569
  "eslint": 8.57.0
  "meilisearch": 0.44.1
  "next": 14.2.15
  "superjson": 2.2.1
  "typescript": 5.5.4
  "zod": 3.23.8

