export const OverlayLines = (): JSX.Element => (
  <svg
    width="1440"
    height="488"
    viewBox="0 0 1440 488"
    fill="none"
    xmlns="http://www.w3.org/2000/svg">
    <g clipPath="url(#clip0_2221_20650)">
      <g opacity="0.2">
        <rect
          x="16"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="41.1787"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="66.3569"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="91.5356"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="116.714"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="141.893"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="167.072"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="192.25"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="217.429"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="242.607"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="267.786"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="292.964"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="318.143"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="343.321"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="368.5"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="393.678"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="418.857"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="444.036"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="469.214"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="494.393"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="519.571"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="544.75"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="569.928"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="595.107"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="620.286"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="645.464"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="670.643"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="695.822"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="721"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="746.179"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="771.357"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="796.536"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="821.714"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="846.893"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="872.072"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="897.25"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="922.429"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="947.607"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="972.786"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="997.965"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1023.14"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1048.32"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1073.5"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1098.68"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1123.86"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1149.04"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1174.21"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1199.39"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1224.57"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1249.75"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1274.93"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1300.11"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1325.29"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1350.46"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1375.64"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1400.82"
          width="1"
          height="488"
          fill="white"
        />
        <rect
          x="1426"
          width="1"
          height="488"
          fill="white"
        />
      </g>
      <g opacity="0.2">
        <rect
          y="472"
          width="1"
          height="1440"
          transform="rotate(-90 0 472)"
          fill="white"
        />
        <rect
          y="445.235"
          width="1"
          height="1440"
          transform="rotate(-90 0 445.235)"
          fill="white"
        />
        <rect
          y="418.471"
          width="1"
          height="1440"
          transform="rotate(-90 0 418.471)"
          fill="white"
        />
        <rect
          y="391.706"
          width="1"
          height="1440"
          transform="rotate(-90 0 391.706)"
          fill="white"
        />
        <rect
          y="364.941"
          width="1"
          height="1440"
          transform="rotate(-90 0 364.941)"
          fill="white"
        />
        <rect
          y="338.177"
          width="1"
          height="1440"
          transform="rotate(-90 0 338.177)"
          fill="white"
        />
        <rect
          y="311.412"
          width="1"
          height="1440"
          transform="rotate(-90 0 311.412)"
          fill="white"
        />
        <rect
          y="284.647"
          width="1"
          height="1440"
          transform="rotate(-90 0 284.647)"
          fill="white"
        />
        <rect
          y="257.882"
          width="1"
          height="1440"
          transform="rotate(-90 0 257.882)"
          fill="white"
        />
        <rect
          y="231.118"
          width="1"
          height="1440"
          transform="rotate(-90 0 231.118)"
          fill="white"
        />
        <rect
          y="204.353"
          width="1"
          height="1440"
          transform="rotate(-90 0 204.353)"
          fill="white"
        />
        <rect
          y="177.588"
          width="1"
          height="1440"
          transform="rotate(-90 0 177.588)"
          fill="white"
        />
        <rect
          y="150.823"
          width="1"
          height="1440"
          transform="rotate(-90 0 150.823)"
          fill="white"
        />
        <rect
          y="124.059"
          width="1"
          height="1440"
          transform="rotate(-90 0 124.059)"
          fill="white"
        />
        <rect
          y="97.2942"
          width="1"
          height="1440"
          transform="rotate(-90 0 97.2942)"
          fill="white"
        />
        <rect
          y="70.5293"
          width="1"
          height="1440"
          transform="rotate(-90 0 70.5293)"
          fill="white"
        />
        <rect
          y="43.7646"
          width="1"
          height="1440"
          transform="rotate(-90 0 43.7646)"
          fill="white"
        />
        <rect
          y="17"
          width="1"
          height="1440"
          transform="rotate(-90 0 17)"
          fill="white"
        />
      </g>
      <rect width="1440" height="488" fill="url(#paint0_radial_2221_20650)"/>
    </g>
    <defs>
      <radialGradient
        id="paint0_radial_2221_20650"
        cx="0"
        cy="0"
        r="1"
        gradientUnits="userSpaceOnUse"
        gradientTransform="translate(720 244) rotate(90) scale(244 720)">
        <stop stopColor="currentColor" stopOpacity="0"/>
        <stop offset="1" stopColor="currentColor"/>
      </radialGradient>
      <clipPath id="clip0_2221_20650">
        <rect width="1440" height="488" fill="white"/>
      </clipPath>
    </defs>
  </svg>
);
