INSERT INTO "ForumQuestion" ("UserId", "Title", "Question", "LegalArea", "LegalField", "LegalTopic")
VALUES
    (:UserId, 'Landlord-Tenant Dispute', 'Can a landlord increase rent without notice?', 'Real Estate Law', 'Landlord-Tenant', 'Rent Increase'),
    (:UserId, 'Intellectual Property Rights', 'How do I protect my software idea?', 'Intellectual Property Law', 'Software', 'Protection'),
    (:UserId, 'Criminal Defense', 'What are the legal consequences for a first-time DUI offense?', 'Criminal Law', 'DUI', 'Legal Consequences'),
    (:UserId, 'Family Law', 'How is child custody determined during divorce proceedings?', 'Family Law', 'Divorce', 'Child Custody'),
    (:UserId, 'Employment Discrimination', 'What actions can I take if I face workplace discrimination?', 'Employment Law', 'Discrimination', 'Legal Actions'),
    (:UserId, 'Contract Law', 'How to interpret ambiguous terms in a contract?', 'Contract Law', NULL, 'Interpretation'),
    (:UserId, 'Environmental Law', 'What are the legal requirements for waste disposal in commercial establishments?', 'Environmental Law', 'Waste Disposal', 'Legal Requirements'),
    (:UserId, 'Personal Injury Claim', 'How to determine the value of a personal injury claim?', 'Personal Injury Law', NULL, 'Claim Valuation'),
    (:UserId, 'Tax Law', 'What are the tax implications of cryptocurrency transactions?', 'Tax Law', 'Cryptocurrency', 'Tax Implications'),
    (:UserId, 'Immigration Law', 'How long does the immigration process typically take?', 'Immigration Law', NULL, 'Processing Time'),
    (:UserId, 'Business Formation', 'What legal steps are involved in starting a small business?', 'Business Law', 'Small Business', 'Legal Steps'),
    (:UserId, 'Medical Malpractice', 'How to pursue a medical malpractice claim?', 'Medical Malpractice', NULL, 'Legal Action'),
    (:UserId, 'Estate Planning', 'What documents are essential for estate planning?', 'Estate Planning', NULL, 'Essential Documents'),
    (:UserId, 'Consumer Rights', 'Can a consumer sue for false advertising?', 'Consumer Protection', 'False Advertising', 'Legal Remedies'),
    (:UserId, 'Insurance Claims', 'What steps should be taken when facing issues with an insurance claim?', 'Insurance Law', NULL, 'Claim Resolution'),
    (:UserId, 'International Business Law', 'How to navigate legal complexities in international business transactions?', 'International Business Law', NULL, 'Legal Complexities'),
    (:UserId, 'Civil Rights', 'What are the legal protections for individuals in cases of discrimination?', 'Civil Rights Law', 'Discrimination', 'Legal Protections'),
    (:UserId, 'Cybersecurity Law', 'What legal measures can be taken to protect against cyber threats?', 'Cybersecurity Law', NULL, 'Legal Measures'),
    (:UserId, 'Bankruptcy Law', 'How does personal bankruptcy affect credit scores?', 'Bankruptcy Law', NULL, 'Credit Impact'),
    (:UserId, 'Employment Contracts', 'What are the key terms to negotiate in an employment contract?', 'Employment Law', 'Contract Negotiation', 'Key Terms'),
    (:UserId, 'Tenant Rights', 'What are the rights of tenants in case of unannounced property inspections?', 'Real Estate Law', 'Landlord-Tenant', 'Tenant Rights'),
    (:UserId, 'Software Licensing', 'What considerations should be taken into account when licensing software to third parties?', 'Intellectual Property Law', 'Software', 'Licensing Considerations'),
    (:UserId, 'Criminal Record Expungement', 'Is it possible to expunge a criminal record, and what is the process involved?', 'Criminal Law', 'Expungement', 'Legal Process'),
    (:UserId, 'Child Support Modification', 'Under what circumstances can child support orders be modified?', 'Family Law', 'Child Support', 'Modification Criteria'),
    (:UserId, 'Workplace Harassment', 'What defines workplace harassment, and how can it be legally addressed?', 'Employment Law', 'Harassment', 'Legal Remedies'),
    (:UserId, 'Breach of Contract', 'How to handle a breach of contract and what legal remedies are available?', 'Contract Law', NULL, 'Breach Handling'),
    (:UserId, 'Environmental Impact Assessment', 'What is the role of an environmental impact assessment in development projects?', 'Environmental Law', 'Impact Assessment', 'Legal Requirements'),
    (:UserId, 'Negligence in Personal Injury Cases', 'How is negligence proven in personal injury cases?', 'Personal Injury Law', 'Negligence', 'Legal Proof'),
    (:UserId, 'Tax Deductions for Small Businesses', 'What tax deductions are available for small businesses?', 'Tax Law', 'Small Business', 'Deductions'),
    (:UserId, 'Permanent Residency Requirements', 'What are the requirements for obtaining permanent residency?', 'Immigration Law', 'Permanent Residency', 'Eligibility Criteria'),
    (:UserId, 'Corporate Governance', 'What are the key principles of corporate governance?', 'Business Law', 'Corporate Governance', 'Principles'),
    (:UserId, 'Patients Right to Informed Consent', 'What does informed consent mean in medical procedures, and what are the legal implications?', 'Medical Law', 'Informed Consent', 'Legal Obligations'),
    (:UserId, 'Revocable Living Trusts', 'What are the advantages and disadvantages of setting up a revocable living trust?', 'Estate Planning', 'Living Trusts', 'Pros and Cons'),
    (:UserId, 'Product Liability Claims', 'How are product liability claims handled, and what are the legal standards?', 'Consumer Protection', 'Product Liability', 'Legal Standards'),
    (:UserId, 'Health Insurance Denials', 'What steps can be taken when a health insurance claim is wrongfully denied?', 'Insurance Law', 'Health Insurance', 'Claim Denial Appeals'),
    (:UserId, 'International Trade Agreements', 'How do international trade agreements impact local businesses?', 'International Trade Law', NULL, 'Local Business Impact'),
    (:UserId, 'Housing Discrimination', 'What constitutes housing discrimination, and how can it be legally addressed?', 'Civil Rights Law', 'Discrimination', 'Legal Remediation'),
    (:UserId, 'Cybersecurity Incident Response', 'What legal measures should be taken in response to a cybersecurity incident?', 'Cybersecurity Law', NULL, 'Incident Response'),
    (:UserId, 'Chapter 7 vs. Chapter 13 Bankruptcy', 'What are the differences between Chapter 7 and Chapter 13 bankruptcy?', 'Bankruptcy Law', 'Bankruptcy Types', 'Comparison'),
    (:UserId, 'Non-Compete Agreements', 'How enforceable are non-compete agreements, and what factors are considered in court?', 'Employment Law', 'Non-Compete', 'Enforceability Criteria'),
    (:UserId, 'Real Estate Development Zoning Laws', 'What zoning laws should be considered in real estate development projects?', 'Real Estate Law', 'Zoning', 'Legal Considerations'),
    (:UserId, 'Software Patents', 'How can one obtain a patent for software, and what are the requirements?', 'Intellectual Property Law', 'Software', 'Patent Acquisition'),
    (:UserId, 'Juvenile Criminal Defense', 'What are the legal rights of juveniles in criminal defense cases?', 'Juvenile Law', 'Criminal Defense', 'Legal Rights'),
    (:UserId, 'Employment Termination Rights', 'What rights do employees have in case of wrongful termination?', 'Employment Law', 'Termination Rights', 'Legal Protections'),
    (:UserId, 'Business Contracts Dispute Resolution', 'What methods are available for resolving business contract disputes?', 'Contract Law', 'Dispute Resolution', 'Legal Avenues'),
    (:UserId, 'Maritime Law', 'How does maritime law apply to shipping and offshore activities?', 'Maritime Law', NULL, 'Legal Application'),
    (:UserId, 'Environmental Conservation Regulations', 'What regulations govern environmental conservation efforts?', 'Environmental Law', 'Conservation Regulations', 'Legal Compliance'),
    (:UserId, 'Defamation Lawsuits', 'What elements must be proven in a defamation lawsuit, and what damages can be sought?', 'Media Law', 'Defamation', 'Legal Elements'),
    (:UserId, 'Automobile Insurance Claims', 'What steps should be taken after a car accident for filing an insurance claim?', 'Insurance Law', 'Auto Insurance', 'Claim Filing'),
    (:UserId, 'International Business Contracts', 'What considerations should be made when drafting international business contracts?', 'International Business Law', 'Contract Drafting', 'Considerations');
