# Step 1: Generate SQL code using pnpm migrations:generate
pnpm run generate-migrations-without-row-level-security

# Step 2: Capture SQL code generated by 'migrations:generate:custom' (which creates an new sql migration file that is empty)
generated_sql=$(pnpm run generate-new-custom-migration)

# Step 3: Extract the SQL file name from the generated output
file_name=$(echo "$generated_sql" | grep -o '\b\S\+\.sql\b')

# Step 4: Append the contents of enable-row-level-security.sql to the extracted file
cat ./src/db/custom-sql/enable-row-level-security.sql >> "$file_name"
